services:
  # 共享层：PostgreSQL (TimescaleDB) 数据库
  postgres:
    image: timescale/timescaledb:latest-pg15
    container_name: share-postgres
    restart: always
    ports:
      - "5001:5432"
    environment:
      - POSTGRES_USER=nick
      - POSTGRES_PASSWORD=nick_postgres_pass
      - POSTGRES_DB=nickdb
    env_file:
      - ../env/share-postgres.env
    deploy:
      resources:
        reservations:
          memory: 256M
    oom_score_adj: -800
    networks:
      - nick-net

volumes:
  share_postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../volumes/share/postgres

networks:
  nick-net:
    external: true
