services:
  # 共享层：PostgreSQL (TimescaleDB) 数据库
  postgres:
    image: timescale/timescaledb:latest-pg15
    container_name: share-postgres
    labels:
      - "nms.collect=true"
      - "nms.layer=share"
      - "nms.proxy=false"
    env_file: .env
    restart: always
    ports:
      - "5001:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    deploy:
      resources:
        reservations:
          memory: 256M
    oom_score_adj: -800
    networks:
      - nms

volumes:
  share_postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MNG_HOME}/volumes/share/postgres

networks:
  nms:
    external: true
